### ISSUE TITLE
How to start ? 

### ISSUE THREAD

**Issue by YouAreBest** [uber/AthenaX#16] opened 2018-01-23 07:18 UTC
In situations where documentation is extremely scarce .  
I try to build environment via http://athenax.readthedocs.io/en/latest/getting_started
But can't find the com. Foo. MyCatalogProvider, I don't find this class, also does not have the detailed case can refer to .
I think detailed documentation is required for open source projects.
thank you

**Comment by walterddr** [comment] 2018-08-02 00:56
you are absolutely right. We are actually moving to Flink 1.5 TableSourceFactory approach as of now. many of our users do find this very confusing

**Comment by walterddr** [comment] 2018-08-02 00:59
close as duplicate of https://github.com/uber/AthenaX/issues/4

**Closed as completed by walterddr** 2018-08-02 00:59 UTC
